VERSION=v2.3
-include ../scripts/common.mk

# 头文件路径
INCLUDES += -I. -I./include 
CXXFLAGS += $(INCLUDES)

# 源文件
DIRS := src
DIRS += g7xx

# 
LIB-build := libg7xx.so

-include ../scripts/common_build.mk